# Generated by Django 4.2.23 on 2025-06-20 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_duration', models.PositiveIntegerField(default=30)),
                ('session_timeout', models.PositiveIntegerField(default=60)),
                ('require_2fa', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('allow_multiple_sessions', models.BooleanField(default=True)),
                ('ip_whitelist_enabled', models.BooleanField(default=False)),
                ('ip_whitelist', models.JSONField(blank=True, default=list)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=365)),
                ('track_user_activities', models.BooleanField(default=True)),
                ('alert_on_suspicious_activity', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='core_logina_usernam_826338_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_logina_ip_addr_55d563_idx'), models.Index(fields=['success', '-timestamp'], name='core_logina_success_d149db_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_STUDENTS', 'View Students'), ('MARK_ATTENDANCE', 'Mark Attendance'), ('USE_FACE_RECOGNITION', 'Use Face Recognition'), ('GENERATE_REPORT', 'Generate Report'), ('UPDATE_STUDENT', 'Update Student'), ('DELETE_ATTENDANCE', 'Delete Attendance'), ('CREATE_STUDENT', 'Create Student'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW_ADMIN_USERS', 'View Admin Users'), ('CREATE_ADMIN_USER', 'Create Admin User'), ('UPDATE_ADMIN_USER', 'Update Admin User'), ('DELETE_ADMIN_USER', 'Delete Admin User'), ('CHANGE_SECURITY_SETTINGS', 'Change Security Settings')], max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_efaa8e_idx'), models.Index(fields=['action', '-timestamp'], name='core_userac_action_b04fa7_idx'), models.Index(fields=['status', '-timestamp'], name='core_userac_status_1c7457_idx')],
            },
        ),
    ]
