# Generated by Django 5.2.1 on 2025-06-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='recognition_model',
            field=models.CharField(default='cnn', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='face_encoding_model',
            field=models.CharField(default='cnn', max_length=10),
        ),
    ]
