# Generated by Django 4.2.23 on 2025-06-26 10:11

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=core.models.generate_session_id, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('session_duration_minutes', models.IntegerField(default=120)),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_auto_closed', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('location_notes', models.TextField(blank=True)),
                ('total_students_expected', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('present_late', 'Present (Late)'), ('absent', 'Absent')], max_length=20)),
                ('recognition_confidence', models.FloatField(blank=True, null=True)),
                ('recognition_model', models.CharField(default='cnn', max_length=20)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_checkins', to='core.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_checkins', to='core.student')),
            ],
            options={
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['session', '-check_in_time'], name='core_sessio_session_d7b5b4_idx'), models.Index(fields=['student', '-check_in_time'], name='core_sessio_student_681cf8_idx'), models.Index(fields=['status', '-check_in_time'], name='core_sessio_status_8d1a27_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
