# Generated by Django 4.2.23 on 2025-06-28 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendancesession_sessioncheckin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['level_order', 'level_name']},
        ),
        migrations.RemoveIndex(
            model_name='sessioncheckin',
            name='core_sessio_session_d7b5b4_idx',
        ),
        migrations.RenameField(
            model_name='attendancesession',
            old_name='location_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='sessioncheckin',
            old_name='session',
            new_name='attendance_session',
        ),
        migrations.AlterUniqueTogether(
            name='sessioncheckin',
            unique_together={('attendance_session', 'student')},
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='is_auto_closed',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department (mainly for teachers and department staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.department'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Auto-generated employee ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_department_head',
            field=models.BooleanField(default=False, help_text='Is this person the head of their department?'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='job_title',
            field=models.CharField(blank=True, help_text="Specific job title (e.g., 'Senior Lecturer', 'IT Administrator')", max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Area of specialization (mainly for teachers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='core.specialization'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='recognition_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='auto_end_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='level',
            name='level_order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='specialization',
            name='duration_years',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='face_images_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='institution_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='institution_name',
            field=models.CharField(default='FACE.IT School', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessioncheckin',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.specialization'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', '-attendance_date'], name='core_attend_student_d55f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['course', '-attendance_date'], name='core_attend_course__7beb25_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status', '-attendance_date'], name='core_attend_status_7ee38b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['course', '-start_time'], name='core_attend_course__3c55c7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['teacher', '-start_time'], name='core_attend_teacher_2f1d75_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', '-start_time'], name='core_attend_status_de26de_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncheckin',
            index=models.Index(fields=['attendance_session', '-check_in_time'], name='core_sessio_attenda_5f59ff_idx'),
        ),
        migrations.RemoveField(
            model_name='sessioncheckin',
            name='is_auto_generated',
        ),
        migrations.RemoveField(
            model_name='sessioncheckin',
            name='recognition_model',
        ),
        migrations.RemoveField(
            model_name='sessioncheckin',
            name='updated_at',
        ),
    ]
