# Generated by Django 4.2.23 on 2025-06-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_timetable_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetableentry',
            new_name='core_timeta_academi_da37d1_idx',
            old_name='core_timetab_academi_c8b2a1_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableentry',
            new_name='core_timeta_teacher_efee2c_idx',
            old_name='core_timetab_teacher_b7c4d3_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableentry',
            new_name='core_timeta_course__587d47_idx',
            old_name='core_timetab_course__e9f1a2_idx',
        ),
    ]
