# Generated by Django 5.2.17 on 2026-09-28 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_core_timetab_academi_c8b2a1_idx_core_timeta_academi_da37d1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncheckin',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
